save: "/content/1D_data/DataEta1_e4/"
dt_save: 0.025
ini_time: 0.
fin_time: 1
nx: 128
ny: 1
nz: 1
xL: -1.
xR: 1.
yL: -1.
yR: 1.
zL: -1.
zR: 1.
bc: "periodic"
gamma: 1.6666666666666667
eta: 1.e-4
zeta: 1.e-2
CFL: 3.e-1
if_second_order: 1.
if_show: 1
show_steps: 1
p_floor: 1.e-4
numbers: 200
init_mode_Multi: "1D_rand"
init_key: 2022
if_rand_param: False
M0: 0.1
